"""Initial migration

Revision ID: df98f5cb327e
Revises: 
Create Date: 2025-02-24 21:38:33.954030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df98f5cb327e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Counties',
    sa.Column('CountyID', sa.Integer(), nullable=False),
    sa.Column('CountyName', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('CountyID')
    )
    op.create_table('Constituencies',
    sa.Column('ConstituencyID', sa.Integer(), nullable=False),
    sa.Column('ConstituencyName', sa.String(length=100), nullable=False),
    sa.Column('CountyID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['CountyID'], ['Counties.CountyID'], ),
    sa.PrimaryKeyConstraint('ConstituencyID')
    )
    op.create_table('Wards',
    sa.Column('WardID', sa.Integer(), nullable=False),
    sa.Column('WardName', sa.String(length=100), nullable=False),
    sa.Column('ConstituencyID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ConstituencyID'], ['Constituencies.ConstituencyID'], ),
    sa.PrimaryKeyConstraint('WardID')
    )
    op.create_table('Projects',
    sa.Column('ProjectID', sa.Integer(), nullable=False),
    sa.Column('ImplementingAgency', sa.String(length=255), nullable=True),
    sa.Column('Program', sa.String(length=255), nullable=True),
    sa.Column('ProjectName', sa.String(length=255), nullable=True),
    sa.Column('CountyID', sa.Integer(), nullable=True),
    sa.Column('ConstituencyID', sa.Integer(), nullable=True),
    sa.Column('WardID', sa.Integer(), nullable=True),
    sa.Column('GPSCoordinates', sa.String(length=50), nullable=True),
    sa.Column('ProjectType', sa.String(length=100), nullable=True),
    sa.Column('ProjectLocation', sa.Enum('Rural', 'Urban'), nullable=True),
    sa.Column('ScopeOfWorks', sa.Text(), nullable=True),
    sa.Column('IntakeCapacity_m3', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('TreatmentCapacity_m3', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('StorageCapacity_m3', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('TreatedWaterMains_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('DistributionLines_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('NumberOfWaterKiosks', sa.Integer(), nullable=True),
    sa.Column('NumberOfConnections', sa.Integer(), nullable=True),
    sa.Column('WastewaterCapacity_m3', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('TargetAreas', sa.String(length=255), nullable=True),
    sa.Column('TargetBeneficiaries_Households', sa.Integer(), nullable=True),
    sa.Column('TargetBeneficiaries_Population', sa.Integer(), nullable=True),
    sa.Column('Contractor', sa.String(length=255), nullable=True),
    sa.Column('Consultant', sa.String(length=255), nullable=True),
    sa.Column('StartDate', sa.Date(), nullable=True),
    sa.Column('PlannedEndDate', sa.Date(), nullable=True),
    sa.Column('ActualEndDate', sa.Date(), nullable=True),
    sa.Column('ProgressPercentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('TotalContractSum_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('CumulativeExpenditure_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('OutstandingCost_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ExchequerReleases_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('SumOfPendingBills_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ApprovedBudgetFY2021_22', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ApprovedBudgetFY2021_23', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ApprovedBudgetFY2022_23', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ApprovedBudgetFY2022_24', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ApprovedBudgetFY2023_24', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ApprovedBudgetFY2023_25', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('BudgetAllocationFY2024_25', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('BudgetAllocationFY2024_26', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ImpactsOfTheProject', sa.Text(), nullable=True),
    sa.Column('KeyChallenges', sa.Text(), nullable=True),
    sa.Column('Remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ConstituencyID'], ['Constituencies.ConstituencyID'], ),
    sa.ForeignKeyConstraint(['CountyID'], ['Counties.CountyID'], ),
    sa.ForeignKeyConstraint(['WardID'], ['Wards.WardID'], ),
    sa.PrimaryKeyConstraint('ProjectID')
    )
    op.create_table('Funding',
    sa.Column('FundingID', sa.Integer(), nullable=False),
    sa.Column('ProjectID', sa.Integer(), nullable=True),
    sa.Column('SourceOfFunds', sa.String(length=255), nullable=True),
    sa.Column('GoK_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('AFD_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ADB_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('EU_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('EIB_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('KfW_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('Belgium_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('Italy_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('Netherlands_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('EXIMBank_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('WB_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('BADEA_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('JICA_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('KOREA_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('OFID_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('SAUDIARABIA_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('DANIDA_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['ProjectID'], ['Projects.ProjectID'], ),
    sa.PrimaryKeyConstraint('FundingID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Funding')
    op.drop_table('Projects')
    op.drop_table('Wards')
    op.drop_table('Constituencies')
    op.drop_table('Counties')
    # ### end Alembic commands ###
