"""Add Funding model

Revision ID: f48dfd6e4180
Revises: d6cd2d5ebc92
Create Date: 2025-02-24 23:22:54.051993

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f48dfd6e4180'
down_revision = 'd6cd2d5ebc92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Counties',
    sa.Column('CountyID', sa.Integer(), nullable=False),
    sa.Column('CountyName', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('CountyID')
    )
    op.create_table('Constituencies',
    sa.Column('ConstituencyID', sa.Integer(), nullable=False),
    sa.Column('ConstituencyName', sa.String(length=100), nullable=False),
    sa.Column('CountyID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['CountyID'], ['Counties.CountyID'], ),
    sa.PrimaryKeyConstraint('ConstituencyID')
    )
    op.create_table('Wards',
    sa.Column('WardID', sa.Integer(), nullable=False),
    sa.Column('WardName', sa.String(length=100), nullable=False),
    sa.Column('ConstituencyID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ConstituencyID'], ['Constituencies.ConstituencyID'], ),
    sa.PrimaryKeyConstraint('WardID')
    )
    op.create_table('Projects',
    sa.Column('ProjectID', sa.Integer(), nullable=False),
    sa.Column('ImplementingAgency', sa.String(length=255), nullable=True),
    sa.Column('Program', sa.String(length=255), nullable=True),
    sa.Column('ProjectName', sa.String(length=255), nullable=True),
    sa.Column('CountyID', sa.Integer(), nullable=True),
    sa.Column('ConstituencyID', sa.Integer(), nullable=True),
    sa.Column('WardID', sa.Integer(), nullable=True),
    sa.Column('GPSCoordinates', sa.String(length=50), nullable=True),
    sa.Column('ProjectType', sa.String(length=100), nullable=True),
    sa.Column('ProjectLocation', sa.Enum('Rural', 'Urban'), nullable=True),
    sa.Column('ScopeOfWorks', sa.Text(), nullable=True),
    sa.Column('IntakeCapacity_m3', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('TreatmentCapacity_m3', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('StorageCapacity_m3', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('TreatedWaterMains_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('DistributionLines_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('NumberOfWaterKiosks', sa.Integer(), nullable=True),
    sa.Column('NumberOfConnections', sa.Integer(), nullable=True),
    sa.Column('WastewaterCapacity_m3', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('TargetAreas', sa.String(length=255), nullable=True),
    sa.Column('TargetBeneficiaries_Households', sa.Integer(), nullable=True),
    sa.Column('TargetBeneficiaries_Population', sa.Integer(), nullable=True),
    sa.Column('Contractor', sa.String(length=255), nullable=True),
    sa.Column('Consultant', sa.String(length=255), nullable=True),
    sa.Column('StartDate', sa.Date(), nullable=True),
    sa.Column('PlannedEndDate', sa.Date(), nullable=True),
    sa.Column('ActualEndDate', sa.Date(), nullable=True),
    sa.Column('ProgressPercentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('TotalContractSum_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('CumulativeExpenditure_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('OutstandingCost_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ExchequerReleases_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('SumOfPendingBills_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ApprovedBudgetFY2021_22', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ApprovedBudgetFY2021_23', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ApprovedBudgetFY2022_23', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ApprovedBudgetFY2022_24', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ApprovedBudgetFY2023_24', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ApprovedBudgetFY2023_25', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('BudgetAllocationFY2024_25', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('BudgetAllocationFY2024_26', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ImpactsOfTheProject', sa.Text(), nullable=True),
    sa.Column('KeyChallenges', sa.Text(), nullable=True),
    sa.Column('Remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ConstituencyID'], ['Constituencies.ConstituencyID'], ),
    sa.ForeignKeyConstraint(['CountyID'], ['Counties.CountyID'], ),
    sa.ForeignKeyConstraint(['WardID'], ['Wards.WardID'], ),
    sa.PrimaryKeyConstraint('ProjectID')
    )
    op.create_table('Funding',
    sa.Column('FundingID', sa.Integer(), nullable=False),
    sa.Column('ProjectID', sa.Integer(), nullable=True),
    sa.Column('SourceOfFunds', sa.String(length=255), nullable=True),
    sa.Column('GoK_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('AFD_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ADB_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('EU_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('EIB_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('KfW_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('Belgium_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('Italy_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('Netherlands_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('EXIMBank_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('WB_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('BADEA_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('JICA_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('KOREA_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('OFID_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('SAUDIARABIA_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('DANIDA_KES', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['ProjectID'], ['Projects.ProjectID'], ),
    sa.PrimaryKeyConstraint('FundingID')
    )
    op.drop_table('projects')
    op.drop_table('funding')
    op.drop_table('constituencies')
    op.drop_table('counties')
    op.drop_table('wards')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wards',
    sa.Column('WardID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('WardName', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('ConstituencyID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ConstituencyID'], ['constituencies.ConstituencyID'], name='wards_ibfk_1'),
    sa.PrimaryKeyConstraint('WardID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('counties',
    sa.Column('CountyID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('CountyName', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('CountyID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('constituencies',
    sa.Column('ConstituencyID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ConstituencyName', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('CountyID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['CountyID'], ['counties.CountyID'], name='constituencies_ibfk_1'),
    sa.PrimaryKeyConstraint('ConstituencyID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('funding',
    sa.Column('FundingID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ProjectID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('SourceOfFunds', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('GoK_KES', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('AFD_KES', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('ADB_KES', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('EU_KES', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('EIB_KES', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('KfW_KES', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('Belgium_KES', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('Italy_KES', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('Netherlands_KES', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('EXIMBank_KES', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('WB_KES', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('BADEA_KES', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('JICA_KES', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('KOREA_KES', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('OFID_KES', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('SAUDIARABIA_KES', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('DANIDA_KES', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['ProjectID'], ['projects.ProjectID'], name='funding_ibfk_1'),
    sa.PrimaryKeyConstraint('FundingID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('projects',
    sa.Column('ProjectID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ImplementingAgency', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Program', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ProjectName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('CountyID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ConstituencyID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('WardID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('GPSCoordinates', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ProjectType', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('ProjectLocation', mysql.ENUM('Rural', 'Urban'), nullable=True),
    sa.Column('ScopeOfWorks', mysql.TEXT(), nullable=True),
    sa.Column('IntakeCapacity_m3', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('TreatmentCapacity_m3', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('StorageCapacity_m3', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('TreatedWaterMains_km', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('DistributionLines_km', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('NumberOfWaterKiosks', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('NumberOfConnections', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('WastewaterCapacity_m3', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('TargetAreas', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('TargetBeneficiaries_Households', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('TargetBeneficiaries_Population', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Contractor', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Consultant', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('StartDate', sa.DATE(), nullable=True),
    sa.Column('PlannedEndDate', sa.DATE(), nullable=True),
    sa.Column('ActualEndDate', sa.DATE(), nullable=True),
    sa.Column('ProgressPercentage', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('TotalContractSum_KES', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('CumulativeExpenditure_KES', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('OutstandingCost_KES', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('ExchequerReleases_KES', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('SumOfPendingBills_KES', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('ApprovedBudgetFY2021_22', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('ApprovedBudgetFY2021_23', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('ApprovedBudgetFY2022_23', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('ApprovedBudgetFY2022_24', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('ApprovedBudgetFY2023_24', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('ApprovedBudgetFY2023_25', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('BudgetAllocationFY2024_25', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('BudgetAllocationFY2024_26', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('ImpactsOfTheProject', mysql.TEXT(), nullable=True),
    sa.Column('KeyChallenges', mysql.TEXT(), nullable=True),
    sa.Column('Remarks', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['ConstituencyID'], ['constituencies.ConstituencyID'], name='projects_ibfk_1'),
    sa.ForeignKeyConstraint(['CountyID'], ['counties.CountyID'], name='projects_ibfk_2'),
    sa.ForeignKeyConstraint(['WardID'], ['wards.WardID'], name='projects_ibfk_3'),
    sa.PrimaryKeyConstraint('ProjectID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Funding')
    op.drop_table('Projects')
    op.drop_table('Wards')
    op.drop_table('Constituencies')
    op.drop_table('Counties')
    # ### end Alembic commands ###
